[package]
name = "rmathlib"
description = "A Rust Port of R's C Library of Special Functions"
version = "1.0.0"
edition = "2021"
authors = [
  "Rik Huijzer <rik@huijzer.xyz>",
  "Jose Storopoli <jose@storopoli.io>",
]
license = "GPL 3.0"
categories = ["science"]
keywords = [
  "rmath",
  "math",
  "probability",
  "statistics",
  "stats",
  "distribution",
]
repository = "https://github.com/poweranalyses-org/rmathlib"


[dependencies]
libm = "0.2"
