name: ci

env:
  CARGO_TERM_COLOR: always

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: null

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Version should be at least 1.43 because that is when f64::EPSILON
        # was introduced, which libm depends on.
        # Next, anything lower than 1.46 was unable to update the registry in
        # GitHub Actions.
        # Next, compiling `cc` requires 1.53.
        # But went for 1.56 because of nicer formatting specifiers.
        toolchain: ['1.56', 'stable', 'beta']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        run: |
          rustup update ${{ matrix.toolchain }}
          rustup default ${{ matrix.toolchain }}
      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: 'test-${{ matrix.rust }}'
      - name: Cargo test
        run: |
          cargo test
          cd test/
          cargo test

  check-format:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          rustup update nightly
          rustup default nightly
          rustup component add clippy
          rustup component add rustfmt

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: 'check-format'

      - name: Cargo clippy
        run: |
          cargo clippy --all-targets --all-features -- -D warnings
          cd test/
          cargo clippy --all-targets --all-features -- -D warnings

      - name: Cargo fmt
        run: |
          # Only available on nightly, unfortunately.
          # Ensures each import has its own `use` statement.
          # This makes it easier to quickly modify the imports in editors.
          echo 'imports_granularity = "Item"' > rustfmt.toml
          cargo fmt --all --check

          cp rustfmt.toml test/
          cd test/
          cargo fmt --all --check

  test-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          rustup update stable
          rustup default stable

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: 'docs'

      - name: Build docs
        env:
          RUSTDOCFLAGS: "-D rustdoc::all -A rustdoc::private-doc-tests"
        run: |
          cargo doc --all --no-deps
          echo '<meta http-equiv="refresh" content="0; url=rmathlib">' > target/doc/index.html
