name: docs

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Stable Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 'stable'

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Build docs
        run: |
          cargo doc --all --no-deps
          echo '<meta http-equiv="refresh" content="0; url=rmathlib">' > target/doc/index.html

      # Not using actions/deploy-pages because it crashes for some reason.
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          cname: 'rmathlib.poweranalyses.org'
          force_orphan: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './target/doc'
