name: docs

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Stable Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 'stable'

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Build docs
        run: cargo doc --package math --no-deps

      - uses: actions/upload-pages-artifact@v3
        if: ${{ github.event_name != 'pull_request' }}
        with:
          path: './target/doc/math'
          retention-days: '1'

  deploy:
    # Separate step to keep the permissions separated.
    needs: build
    if: ${{ github.event_name != 'pull_request' }}
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
